ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host:     "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port:     5432
      user:     "{{ env_var('POSTGRES_USER', 'analytics') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'analytics') }}"
      dbname:   "{{ env_var('POSTGRES_DB', 'ecommerce') }}"
      schema:   raw
      threads:  4
